updates to apps

diff --git a/apps/gemfire-statefulset.yaml b/apps/gemfire-statefulset.yaml
--- a/apps/gemfire-statefulset.yaml
+++ b/apps/gemfire-statefulset.yaml
@@ -26,7 +26,7 @@ spec:
         app: gemfire-locator
     spec:
       imagePullSecrets:
-      - name: docker # Updated secret name
+      - name: docker # Add imagePullSecrets
       containers:
       - name: gemfire-locator
         image: gemfire/gemfire-all:10.1-jdk17
@@ -39,14 +39,16 @@ spec:
         - start
         - locator
         - --name=locator-0
-        - --hostname-for-clients=$(POD_IP) # Use POD_IP for client access
-        - --J='-Dgemfire.jmx-manager-hostname-for-clients=$(POD_IP)'
+        - --hostname-for-clients=gemfire-locator-service.default.svc.cluster.local #$(POD_IP) # Use POD_IP for client access
+        - --J='-Dgemfire.jmx-manager-hostname-for-clients=gemfire-locator-service.default.svc.cluster.local'
+        - --dir=/data/$(POD_NAME) # Use unique directory for each locator instance
         env:
         - name: ACCEPT_TERMS
           value: "y"
-        # envFrom: # Optional: If you have a ConfigMap for env vars
-        # - configMapRef:
-        #     name: gemfire-config # Replace with your ConfigMap name
+        - name: POD_NAME
+          valueFrom:
+            fieldRef:
+              fieldPath: metadata.name
         readinessProbe: # Kubernetes readiness probe
           httpGet:
             path: /management/v1/members/locator-0
@@ -59,8 +61,8 @@ spec:
             cpu: 1
             memory: 2Gi
           limits:
-            cpu: 2
-            memory: 4Gi
+            cpu: 1
+            memory: 2Gi
         volumeMounts: # If you need persistence
         - name: gemfire-data
           mountPath: /data
@@ -119,8 +121,31 @@ spec:
       labels:
         app: gemfire-server
     spec:
+      restartPolicy: Always # Ensure the pod is restarted on failures
       imagePullSecrets:
-      - name: docker # Updated secret name
+      - name: docker # Add imagePullSecrets
+      initContainers:
+      - name: wait-for-locator
+        image: nicolaka/netshoot:latest
+        env:
+        - name: LOCATOR_POD_IP
+          valueFrom:
+            fieldRef:
+              fieldPath: status.podIP
+        command:
+        - sh
+        - -c
+        - |
+          count=0
+          until nc -zv $GEMFIRE_LOCATOR_SERVICE_PORT_10334_TCP_ADDR 10334 || [ $count -eq 5 ]; do
+            echo waiting for gemfire-locator-service
+            sleep 2
+            count=$((count + 1))
+          done
+          if [ $count -eq 5 ]; then
+            echo "Failed to connect to gemfire-locator-service after 5 attempts"
+            exit 1
+          fi
       containers:
       - name: gemfire-server
         image: gemfire/gemfire-all:10.1-jdk17
@@ -133,7 +158,7 @@ spec:
         - start
         - server
         - --name=server-0
-        - --locators=gemfire-locator-service.default.svc.cluster.local[10334]# Use headless service name
+        - --locators=gemfire-locator-service.default.svc.cluster.local[10334] # Ensure correct service name and namespace
         - --start-rest-api
         - --http-service-port=7070
         env:
@@ -142,28 +167,27 @@ spec:
         # envFrom: # Optional: If you have a ConfigMap for env vars
         # - configMapRef:
         #     name: gemfire-config # Replace with your ConfigMap name
-        readinessProbe:
-          httpGet:
-            path: /gemfire-api/v1/ping
-            port: 7070
-          initialDelaySeconds: 5
-          periodSeconds: 5
-          failureThreshold: 5
+        # readinessProbe:
+        #   httpGet:
+        #     path: /gemfire-api/v1/ping
+        #     port: 7070
+        #   initialDelaySeconds: 5
+        #   periodSeconds: 5
+        #   failureThreshold: 5
         resources:
           requests:
             cpu: 1
             memory: 2Gi
           limits:
             cpu: 2
-            memory: 4Gi
+            memory: 2Gi
         volumeMounts: # If you need persistence
         - name: gemfire-data
           mountPath: /data
       volumes: # If you need persistence
       - name: gemfire-data
         persistentVolumeClaim:
-          claimName: gemfire-pvc # Replace with your PVC name
-
+          claimName: gemfire-pvc-server # Replace with your PVC name
 ---
 apiVersion: v1
 kind: Service
@@ -186,7 +210,6 @@ spec:
     targetPort: 40405
     name: locator
   type: ClusterIP # or NodePort, LoadBalancer based on your requirement
-
 ---
 apiVersion: apps/v1
 kind: Deployment
@@ -203,7 +226,7 @@ spec:
         app: management-console
     spec:
       imagePullSecrets:
-      - name: docker # Updated secret name
+      - name: docker # Add imagePullSecrets
       containers:
       - name: management-console
         image: gemfire/gemfire-management-console:latest
@@ -223,7 +246,6 @@ spec:
           limits:
             cpu: 2
             memory: 2Gi
-
 ---
 apiVersion: v1
 kind: Service
@@ -237,12 +259,22 @@ spec:
     port: 8080
     targetPort: 8080
   type: ClusterIP # or ClusterIP, NodePort based on your requirement
-
 ---
 apiVersion: v1
 kind: PersistentVolumeClaim # If you need persistence
 metadata:
   name: gemfire-pvc
+spec:
+  accessModes: [ "ReadWriteOnce" ] # Or ReadWriteMany if your storage supports it
+  resources:
+    requests:
+      storage: 10Gi # Adjust as needed
+
+---
+apiVersion: v1
+kind: PersistentVolumeClaim # If you need persistence
+metadata:
+  name: gemfire-pvc-server
 spec:
   accessModes: [ "ReadWriteOnce" ] # Or ReadWriteMany if your storage supports it
   resources:
